config/routes.rb
Rails.application.routes.draw do
  resources :instructions
  root 'application#home'
  resources :ingredients
  resources :items
  resources :planned_meals
  resources :recipes do
    resources :planned_meals, only: [:new] #adds recipe to meal plan
  end
  resources :users do
    resources :recipes, only: [:index] #shows all recipes authored by a user
    resources :planned_meals, only: [:index] #shows user's meal plan
  end
  
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/planned_meal.rb
class PlannedMeal < ApplicationRecord
  belongs_to :recipe
  belongs_to :planner, :class_name => "User", :foreign_key => "planner_id"
  validates :date, :presence => {:message => "can't be blank"}
  validates :meal_type, :presence => {:message => "can't be blank"}
  scope :meal_plan, ->(start_date, end_date) { where("date BETWEEN ? AND ?", start_date, end_date) if start_date.present? }

end

app/controllers/planned_meals_controller.rb
class PlannedMealsController < ApplicationController

  def index
    if @planner = User.find_by_id(params[:user_id])
      @planned_meals = @planner.planned_meals
      params[:start_date] && !params[:start_date].empty? ? (@start_date = params[:start_date].to_date) : (@start_date = Date.today)
      @day_2 = @start_date + 1.day
      @day_3 = @start_date + 2.days
      @day_4 = @start_date + 3.days
      @day_5 = @start_date + 4.days
      @day_6 = @start_date + 5.days
      @day_7 = @start_date + 6.days
      @day_8 = @start_date + 7.days
      @day_9 = @start_date + 8.days
      @day_10 = @start_date + 9.days
      @day_11 = @start_date + 10.days
      @day_12 = @start_date + 11.days
      @day_13 = @start_date + 12.days
      @end_date = @start_date + 13.days
      @planned_meals = @planner.planned_meals.meal_plan(@start_date, @end_date)
    else
      redirect_to root_path
    end

  end
  
  def new
    if @recipe = Recipe.find_by_id(params[:recipe_id])
      @planned_meal = @recipe.planned_meals.build
    else
      @planned_meal = PlannedMeal.new
      @recipes = Recipe.alpha
    end
  end

  def create
    @planned_meal = PlannedMeal.new(planned_meal_params)
    @planned_meal.planner = current_user
    if @planned_meal.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  private

  def planned_meal_params
    params.require(:planned_meal).permit(:recipe_id, :date, :meal_type)
  end

end

app/helpers/planned_meals_helper.rb
module PlannedMealsHelper
end

app/views/planned_meals/index.html.erb
<h2>My Meal Plan</h2>

<p>
<%= link_to "+ add a recipe to my meal plan", new_planned_meal_path %>
</p>
<%= form_tag("/planned_meals", method: 'get') do %>
  <%= hidden_field_tag(:user_id, @planner.id) if params[:user_id] %>
  <%= label_tag(:start_date, "When would you like to start your 2-week meal plan?") %>
  <%= date_field_tag(:start_date) %>
  <%= submit_tag("Show me my meal plan") %>
<% end %>
<div class="meal-planner">
<table>
  <tr>
    <th colspan="7"><h2><%= @start_date.strftime("%B") %></h2></th>
  </tr>
  <tr>
    <th><%= @start_date.strftime("%A") %></th>
    <th><%= @day_2.strftime("%A") %></th>
    <th><%= @day_3.strftime("%A") %></th>
    <th><%= @day_4.strftime("%A") %></th>
    <th><%= @day_5.strftime("%A") %></th>
    <th><%= @day_6.strftime("%A") %></th>
    <th><%= @day_7.strftime("%A") %></th>
  </tr>
  <tr>
    <td>
    <%= @start_date.day %>
    <ul>
    <% @planned_meals.each do |planned_meal| %>
        <li><%= link_to "#{planned_meal.meal_type}: #{planned_meal.recipe.name}", recipe_path(planned_meal.recipe) if planned_meal.date == @start_date %></li>
    <% end %>
    </ul>
    </td>
    <td>
    <%= @start_date.month == @day_2.month ? (@day_2.day) : (@day_2.strftime("%b %-d")) %>
    <ul>
    <% @planned_meals.each do |planned_meal| %>
        <li><%= link_to "#{planned_meal.meal_type}: #{planned_meal.recipe.name}", recipe_path(planned_meal.recipe) if planned_meal.date == @day_2 %></li>
    <% end %>
    </ul>
    </td>
    <td>
    <%= @day_2.month == @day_3.month ? (@day_3.day) : (@day_3.strftime("%b %-d") ) %>
    <ul>
    <% @planned_meals.each do |planned_meal| %>
        <li><%= link_to "#{planned_meal.meal_type}: #{planned_meal.recipe.name}", recipe_path(planned_meal.recipe) if planned_meal.date == @day_3 %></li>
    <% end %>
    </ul>
    </td>
    <td>
    <%= @day_3.month == @day_4.month ? (@day_4.day) : (@day_4.strftime("%b %-d") ) %>
    <ul>
    <% @planned_meals.each do |planned_meal| %>
        <li><%= link_to "#{planned_meal.meal_type}: #{planned_meal.recipe.name}", recipe_path(planned_meal.recipe) if planned_meal.date == @day_4 %></li>
    <% end %>
    </ul>
    </td>
    <td>
    <%= @day_4.month == @day_5.month ? (@day_5.day) : (@day_5.strftime("%b %-d") ) %>
    <ul>
    <% @planned_meals.each do |planned_meal| %>
        <li><%= link_to "#{planned_meal.meal_type}: #{planned_meal.recipe.name}", recipe_path(planned_meal.recipe) if planned_meal.date == @day_5 %></li>
    <% end %>
    </ul>
    </td>
    <td>
    <%= @day_5.month == @day_6.month ? (@day_6.day) : (@day_6.strftime("%b %-d") ) %>
    <ul>
    <% @planned_meals.each do |planned_meal| %>
        <li><%= link_to "#{planned_meal.meal_type}: #{planned_meal.recipe.name}", recipe_path(planned_meal.recipe) if planned_meal.date == @day_6 %></li>
    <% end %>
    </ul>
    </td>
    <td>
    <%= @day_6.month == @day_7.month ? (@day_7.day) : (@day_7.strftime("%b %-d") ) %>
    <ul>
    <% @planned_meals.each do |planned_meal| %>
        <li><%= link_to "#{planned_meal.meal_type}: #{planned_meal.recipe.name}", recipe_path(planned_meal.recipe) if planned_meal.date == @day_7 %></li>
    <% end %>
    </ul>
    </td>
  </tr>
  <tr>
  <td>
  <%= @day_7.month == @day_8.month ? (@day_8.day) : (@day_8.strftime("%b %-d") ) %>
    <ul>
    <% @planned_meals.each do |planned_meal| %>
        <li><%= link_to "#{planned_meal.meal_type}: #{planned_meal.recipe.name}", recipe_path(planned_meal.recipe) if planned_meal.date == @day_88 %></li>
    <% end %>
    </ul>
  </td>
  <td>
  <%= @day_8.month == @day_9.month ? (@day_9.day) : (@day_9.strftime("%b %-d")) %>
  <ul>
  <% @planned_meals.each do |planned_meal| %>
      <li><%= link_to "#{planned_meal.meal_type}: #{planned_meal.recipe.name}", recipe_path(planned_meal.recipe) if planned_meal.date == @day_9 %></li>
  <% end %>
  </ul>
  </td>
  <td>
  <%= @day_9.month == @day_10.month ? (@day_10.day) : (@day_10.strftime("%b %-d") ) %>
  <ul>
  <% @planned_meals.each do |planned_meal| %>
      <li><%= link_to "#{planned_meal.meal_type}: #{planned_meal.recipe.name}", recipe_path(planned_meal.recipe) if planned_meal.date == @day_10 %></li>
  <% end %>
  </ul>
  </td>
  <td>
  <%= @day_10.month == @day_11.month ? (@day_11.day) : (@day_11.strftime("%b %-d") ) %>
  <ul>
  <% @planned_meals.each do |planned_meal| %>
      <li><%= link_to "#{planned_meal.meal_type}: #{planned_meal.recipe.name}", recipe_path(planned_meal.recipe) if planned_meal.date == @day_11 %></li>
  <% end %>
  </ul>
  </td>
  <td>
  <%= @day_11.month == @day_12.month ? (@day_12.day) : (@day_12.strftime("%b %-d") ) %>
  <ul>
  <% @planned_meals.each do |planned_meal| %>
      <li><%= link_to "#{planned_meal.meal_type}: #{planned_meal.recipe.name}", recipe_path(planned_meal.recipe) if planned_meal.date == @day_12 %></li>
  <% end %>
  </ul>
  </td>
  <td>
  <%= @day_12.month == @day_13.month ? (@day_13.day) : (@day_13.strftime("%b %-d") ) %>
  <ul>
  <% @planned_meals.each do |planned_meal| %>
      <li><%= link_to "#{planned_meal.meal_type}: #{planned_meal.recipe.name}", recipe_path(planned_meal.recipe) if planned_meal.date == @day_13 %></li>
  <% end %>
  </ul>
  </td>
  <td>
  <%= @day_13.month == @end_date.month ? (@end_date.day) : (@end_date.strftime("%b %-d") ) %>
  <ul>
  <% @planned_meals.each do |planned_meal| %>
      <li><%= link_to "#{planned_meal.meal_type}: #{planned_meal.recipe.name}", recipe_path(planned_meal.recipe) if planned_meal.date == @end_date %></li>
  <% end %>
  </ul>
  </td>
</tr>
</table>
</div>

app/views/planned_meals/new.html.erb
<% if @planned_meal.errors.any? %>
  <div class="error">
  <ul>
  <% @planned_meal.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
  </div>
<% end %>


<%= form_for @planned_meal do |f| %>
  <% if params[:recipe_id] %>
    <%= f.hidden_field :recipe_id %>
  <% else %>
    <div>
      <%= f.label :recipe_id, "Select a Recipe" %>
      <%= f.collection_select :recipe_id, @recipes, :id, :name, include_blank: true %>
    </div>
    <br>
  <% end %>
  <div>
  <%= f.label :date %>
  <%= f.date_select :date %>
  </div>
  <br>
  <div>
  <%= f.label :meal_type %>
  <%= f.select :meal_type, [ 'Breakfast', 'Morning Snack', 'Lunch', 'Afternoon Snack', 'Dinner', 'Late Night Snack' ], :prompt => 'Select One' %>
  </div>
  <br>
  <%= f.submit "Submit" %>
<% end %>