config/routes.rb
Rails.application.routes.draw do
  resources :instructions
  root 'application#home'
  resources :ingredients
  resources :items
  resources :planned_meals
  resources :recipes do
    resources :planned_meals, only: [:new] #adds recipe to meal plan
  end
  resources :users do
    resources :recipes, only: [:index] #shows all recipes authored by a user
    resources :planned_meals, only: [:index] #shows user's meal plan
  end
  
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user
  validates :provider, :uid, :presence => true
end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :item
  belongs_to :recipe
  validates :quantity, :presence => {:message => "can't be blank"}
  validate :valid_quantity?
  accepts_nested_attributes_for :item

  def valid_quantity?
    if !self.quantity.to_r.rationalize(0.05)
      errors.add(:quantity, "is invalid")
    end
  end

  def item_name
    item && item.name
  end

  def item_name=(name)
    self.item = Item.find_or_initialize_by(name: name)
  end

end

app/models/instruction.rb
class Instruction < ApplicationRecord
    belongs_to :recipe
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :ingredients
  has_many :recipes, :through => :ingredients
  validates :name, :presence => {:message => "can't be blank"}
  validates :name, :uniqueness => {:message => "already exists" }
end

app/models/planned_meal.rb
class PlannedMeal < ApplicationRecord
  belongs_to :recipe
  belongs_to :planner, :class_name => "User", :foreign_key => "planner_id"
  validates :date, :presence => {:message => "can't be blank"}
  validates :meal_type, :presence => {:message => "can't be blank"}
  scope :meal_plan, ->(start_date, end_date) { where("date BETWEEN ? AND ?", start_date, end_date) if start_date.present? }

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :planned_meals
  has_many :planners, :through => :planned_meals, :class_name => "User", :foreign_key => "planner_id"
  belongs_to :author, :class_name => "User", :foreign_key => "author_id"
  has_many :ingredients, dependent: :destroy
  has_many :items, :through => :ingredients
  has_many :instructions, dependent: :destroy
  validates :name, :presence => {:message => "can't be blank"}
  validates :prep_time, :numericality => { only_integer: true, allow_nil: true, message: "must be a number"}
  validates :cook_time, :numericality => { only_integer: true, allow_nil: true, message: "must be a number"}
  validates :serving_size, :numericality => { only_integer: true, allow_nil: true, message: "must be a number"}
  validates :calories, :numericality => { only_integer: true, allow_nil: true, message: "must be a number"}
  validates :instructions, :presence => {:message => "can't be blank"}
  scope :alpha, -> { order(:name) }
  scope :quick_recipes, -> { where("prep_time <= 30") }
  scope :simple_recipes, -> { where("ingredients.count <= 5")}
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: proc { |attr| attr['item_name'].blank? }
  accepts_nested_attributes_for :instructions, allow_destroy: true, reject_if: proc { |attr| attr['step'].blank? }

def total_time
  self.prep_time.to_i + self.cook_time.to_i
end

end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :item
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :authorizations
  has_many :planned_meals, :foreign_key => "planner_id"
  has_many :recipes, :through => :planned_meals, :foreign_key => "planner_id"
  has_many :recipes, :foreign_key => "author_id"
  validates :username, :presence => {:message => "can't be blank"}
  validates :username, :uniqueness => {:message => "has already been used" }
  validates :email, :presence => {:message => "can't be blank"}
  validates :email, :uniqueness => {:message => "has already been used" }
  validates :email, :format => { with: /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/, :message => "must be an email" }
  validates :password, :length => { minimum: 8, :message => "must be at least 8 characters"}

  def self.create_by_google_omniauth(auth)
    self.find_or_create_by(email: auth['info']['email']) do |u|
      u.name = auth['info']['name']
      u.password = SecureRandom.hex
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:index]

  def index
    if @author = User.find_by_id(params[:user_id])
      @recipes = @author.recipes
    else
      @recipes = Recipe.all
    end
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.author = current_user
    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, :prep_time, :cook_time, :serving_size, :calories, ingredients_attributes: [:_destroy, :id, :quantity, :unit, :item_name, :notes], instructions_attributes: [:_destroy, :id, :step])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    if params[:provider] == 'google_oauth2' && @user = User.find_by(email: auth['info']['email']) #checks to see if logging in using oauth and has logged in before
      session[:user_id] = @user.id
      redirect_to recipes_path

    elsif params[:provider] == 'google_oauth2'
      session[:omniauth] = auth.except('extra')
      redirect_to signup_path
  
    else 
      @user = User.find_by(username: params[:user][:username]) 
      
      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to recipes_path
      else
        flash[:error] = "Login failed. Please try again."
        redirect_to login_path
      end

    end

  end

  def destroy
    session.delete :user_id
    redirect_to root_url
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new

    #Pass omniauth params to the new user form fields when a user uses omniauth to create new account.
    if @auth = session[:omniauth]
      @name = @auth['info']['name']
      @email = @auth['info']['email']
      @password = SecureRandom.hex
    end

  end

  def create
    @user = User.new(user_params)

    if @user.save && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to recipes_path
      session.delete :omniauth  if session[:omniauth]
    else
      render :new
    end

  end

  def show
    @user = User.find(params[:id])
    @message = params[:message] if params[:message]
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/planned_meals_helper.rb
module PlannedMealsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/recipes/_form.html.erb
<% if @recipe.errors.any? %>
  <div class="error">
  <ul>
  <% @recipe.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
  </div>
<% end %>

<%= form_for @recipe do |f| %>
  <div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>
  <div class="field">
  <%= f.label :description %><br>
  <%= f.text_area :description %>
  </div>
  <div class="field">
  <%= f.label :prep_time %><span class="notes">(in minutes)</span>
  <%= f.text_field :prep_time %>
  </div>
  <div class="field">
  <%= f.label :cook_time %><span class="notes">(in minutes)</span>
  <%= f.text_field :cook_time %>
  </div>
  <div class="field">
  <%= f.label :serving_size %>
  <%= f.text_field :serving_size %>
  </div>
  <div class="field">
  <%= f.label :calories %>
  <%= f.text_field :calories %>
  </div>

  <h4>Ingredients</h4>

    <div data-controller="nested-form">
      <template data-target='nested-form.template'>
        <%= f.fields_for :ingredients, Ingredient.new, child_index: 'TEMPLATE_RECORD' do |ingredient| %>
          <%= render 'ingredient_fields', form: ingredient %>
        <% end %>
      </template>

      <%= f.fields_for :ingredients do |ingredient| %>
        <%= render 'ingredient_fields', form: ingredient %>
      <% end %>
     
      <div data-target="nested-form.add_item">
      <small>
      <br>
        <%= link_to "Add ingredient", "#", data: { action: "nested-form#add_association" } %>
      </small>
      </div>
    </div>

  <h4>Instructions</h4>

    <div data-controller="nested-form">
    
      <template data-target='nested-form.template'>
        <%= f.fields_for :instructions, Instruction.new, child_index: 'TEMPLATE_RECORD' do |instruction| %>
          <%= render 'instruction_fields', form: instruction %></li>
        <% end %>
      </template>

      <%= f.fields_for :instructions do |instruction| %>
        <%= render 'instruction_fields', form: instruction %>
      <% end %>
     
      <div data-target="nested-form.add_item">
      <small>
      <br>
        <%= link_to "Add step", "#", data: { action: "nested-form#add_association" } %>
      </small>
      </div>
    </div>

  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class='nested-fields'>
  <div class='form-group'>
    <%= form.hidden_field :_destroy %>
    <div class="field">
    <%= form.text_field :quantity, size: '4', placeholder: 'qty' %> 
    <%= form.text_field :unit, size: '10',  placeholder: 'unit' %> 
    <%= form.text_field :item_name, size: '25', placeholder: 'item' %> <!-- find or create item -->
    <%= form.text_field :notes, size: '50', placeholder: 'notes' %>
    
    <small>
      <%= link_to "Delete", "#", data: { action: "click->nested-form#remove_association" } %>
    </small>
    </div>
  </div>
</div>

app/views/recipes/_instruction_fields.html.erb
<div class='nested-fields'>
  <div class='form-group'>
    <%= form.hidden_field :_destroy %>
    <div class="field">
    <%= form.text_field :step, size: '100', placeholder: 'enter step here' %>
    
    <small>
      <%= link_to "Delete", "#", data: { action: "click->nested-form#remove_association" } %>
    </small>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<h2>Edit Your Recipe</h2>

<%= render partial: 'form'%>

app/views/recipes/index.html.erb
<ul>
<% @recipes.each do |recipe| %>
    <li><b><%= link_to recipe.name, recipe_path(recipe) %></b> <i>by <%= recipe.author.username %></i></li>
<% end %>
</ul>

app/views/recipes/new.html.erb
<h2>Add a Recipe</h2>

<% if @recipe.errors.any? %>
  <div class="error">
  <ul>
  <% @recipe.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
  </div>
<% end %>

<%= form_for @recipe do |f| %>
  <div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
  </div>
  <div class="field">
  <%= f.label :description %><br>
  <%= f.text_area :description %>
  </div>
  <div class="field">
  <%= f.label :prep_time %>
  <%= f.text_field :prep_time %>
  </div>
  <div class="field">
  <%= f.label :cook_time %>
  <%= f.text_field :cook_time %>
  </div>
  <div class="field">
  <%= f.label :serving_size %>
  <%= f.text_field :serving_size %>
  </div>
  <div class="field">
  <%= f.label :calories %>
  <%= f.text_field :calories %>
  </div>

  <h4>Ingredients</h4>

    <div data-controller="nested-form">
      <template data-target='nested-form.template'>
        <%= f.fields_for :ingredients, Ingredient.new, child_index: 'TEMPLATE_RECORD' do |ingredient| %>
          <%= render 'ingredient_fields', form: ingredient %>
        <% end %>
      </template>

      <%= f.fields_for :ingredients do |ingredient| %>
        <%= render 'ingredient_fields', form: ingredient %>
      <% end %>
     
      <div data-target="nested-form.add_item">
      <small>
      <br>
        <%= link_to "Add ingredient", "#", data: { action: "nested-form#add_association" } %>
      </small>
      </div>
    </div>

  <h4>Instructions</h4>

    <div data-controller="nested-form">
    
      <template data-target='nested-form.template'>
        <%= f.fields_for :instructions, Instruction.new, child_index: 'TEMPLATE_RECORD' do |instruction| %>
          <%= render 'instruction_fields', form: instruction %></li>
        <% end %>
      </template>

      <%= f.fields_for :instructions do |instruction| %>
        <%= render 'instruction_fields', form: instruction %>
      <% end %>
     
      <div data-target="nested-form.add_item">
      <small>
      <br>
        <%= link_to "Add step", "#", data: { action: "nested-form#add_association" } %>
      </small>
      </div>
    </div>

  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/recipes/show.html.erb
<div class="recipe-header">
<h2><%= @recipe.name %></h2>
<span><%= link_to "+ edit recipe", edit_recipe_path(@recipe) if @recipe.author == current_user %></span>
<span><%= link_to "+ add to meal plan", new_recipe_planned_meal_path(@recipe) %></span>
</div>
<div>
    <p><i>Submitted by: <%= @recipe.author.username %></i></p>
</div>
<div>
 <p><%= @recipe.description %></div></p>
<div>
<p>
<% if @recipe.prep_time %>
Prep Time: <%= @recipe.prep_time %> minutes
<br>
<% end %>
<% if @recipe.cook_time %>
Cook Time: <%= @recipe.cook_time %> minutes
<br>
<% end %>
<% if @recipe.prep_time || @recipe.cook_time %>
Total Time: <%= @recipe.total_time %> minutes
<br>
<% end %>
<% if @recipe.serving_size %>
Serving Size: <%= @recipe.serving_size %>
<% end %>
<% if @recipe.calories %>
<br>
Calories: <%= @recipe.calories %>
<% end %>
</p>
</div>

<h4>Ingredients:</h4>
<ul>
<% @recipe.ingredients.each do |ingredient| %>
    <li><%= ingredient.quantity %> <%= ingredient.unit %> <%= ingredient.item_name %> <span class="notes"><%= ingredient.notes%></span></li>
  <% end %>
</ul>

<h4>Instuctions:</h4>
<ol>
<% @recipe.instructions.each do |instruction| %>
    <li><%= instruction.step %></li>
  <% end %>
</ol>

app/views/users/_form.html.erb
<%= form_for :user, url: '/users' do |f| %>
    <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>
    <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
    </div>
    <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
    </div>
    <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
    </div>
    <div class="actions">
    <%= f.submit "Sign up" %>
    </div>
  <% end %>

app/views/users/_oauth.html.erb
<%= form_for :user, url: '/users' do |f| %>
  <%= f.hidden_field :name, :value => "#{@name}" %>
  <%= f.hidden_field :email, :value => "#{@email}" %>
  <%= f.hidden_field :password, :value => "#{@password}" %>
  <%= f.label :username, "Choose a username to finish setting up your account:" %>
  <%= f.text_field :username %>
  <br>
  <%= f.submit "Submit" %>
<% end %>

app/views/users/new.html.erb
<div class="center">

<h2>Sign Up</h2>

<% if @user.errors.any? %>
  <div class="error">
  <p>
  <% @user.errors.full_messages.each do |msg| %>
    <%= msg %>.<br>
  <% end %>
  </p>
  </div>
<% end %>

<% if @auth %>
<%= render partial: 'oauth'%>
<% else %>
<%= render partial: 'form'%>
<% end %>

</div>

app/views/users/show.html.erb
<h2>@<%= @user.username %></h2>
<h4><%= @user.name %></h4>
<p><%= link_to "Recipes", user_recipes_path(@user) %>
<br><%= link_to "Planned Meals", user_planned_meals_path(@user) %></p>